### ISSUE TITLE
Plugin not found

### ISSUE THREAD

**Issue by amirebrahimi** [oprypin/mkdocs-gen-files#10]
When I try and run mkdocs with the following config file I get an error:
`Error: Invalid Plugins configuration`

```
site_name: qtcodes

theme:
  name: "material"

plugins:
  - search
  - gen-files:
    scripts:
    - docs/gen_ref_pages.py    
  - mkdocstrings:
```

Thoughts?

**Comment by StarfallProjects** [comment]
Hiya! I'm not the owner, just another person with a question, but I think you might want:

```
plugins:
  - search
  - gen-files:
      scripts:
        - <path-to-you-redirects>.py
```
     
Note how `scripts` is indented.
