### ISSUE TITLE
Generated images are not persistent with build/gh-deploy

### ISSUE THREAD

**Issue by ewuerger** [oprypin/mkdocs-gen-files#14]
Hi mkdocs-gen-files devs!

Thank you very much for this useful plugin. I'm close to publishing my first documentation based on mkdocs, but I have a problem probably based on missing understanding of the underlying of your (Material for MkDocs or even basic MkDocs) plugin:

I'm generating images (SVG files) beside having `gen_ref_pages.py` which generates the Code reference of my library. The SVG files are created under an assets/images folder in docs. I want to use the command `mkdocs gh-deploy --force` in the end such that the images appear in the assets/images folder. But somehow there is only a favicon.png.

I tried it with `mkdocs_gen_files` like seen here:
``` python
diag: diagram.Diagram = model.by_uuid(uuid).context_diagram
with mkdocs_gen_files.open(f"{str(dest / diag.name)}.svg", "w") as fd:
    print(diag.as_svg, file=fd)
```

and while debugging I see that the SVGs are generated at the right location. But somehow during build there are no SVGs kept. Are the SVGs deleted again or is MkDocs ignoring them? Reading through [this](https://github.com/squidfunk/mkdocs-material/discussions/3424) and [this](https://squidfunk.github.io/mkdocs-material/customization/#adding-assets) didn't help unfortunately. I hope someone of you knows how to fix this or gives a helpful hint :smiley: .

Thanks in advance.

**Comment by oprypin** [comment]
Do you have a complete runnable example, not just a truncated snippet?

**Comment by ewuerger** [comment]
Thank you for the blazing fast answer. I tried it with an example SVG set as a constant and it worked. So in order to get the same functionality you'll need to run:
```bash
pip install capellambse
```
and install our library that renders SVGs (MBSE diagrams).

`gen_test_svg.py`:
```python
import pathlib

import mkdocs_gen_files

# Example from https://www.w3schools.com/graphics/tryit.asp?filename=trysvg_rect
svg = """\
<svg width="400" height="110">
  <rect width="300" height="100" style="fill:rgb(0,0,255);stroke-width:3;stroke:rgb(0,0,0)" />
  Sorry, your browser does not support inline SVG.  
</svg>\
"""

dest = pathlib.Path("assets") / "images"
with mkdocs_gen_files.open(f"{dest}/test.svg", "w") as fd:
    fd.write(svg)
```

with the following mkdocs.yml:
```yaml
site_name: Simple example
repo_name: Simple example
repo_url: https://github.com/ewuerger/

theme:
  name: material
  icon:
    repo: fontawesome/brands/github-square
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - content.code.annotate
    - content.tooltips

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - toc:
      permalink: "🔗"

plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_test_svg.py
  - section-index
  - autorefs

nav:
  - Home: index.md
extra_css:
  - css/base.css

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://dsd-dbs.github.io/
```

and `index.md` under docs/:
``` markdown
This should display something:

<figure markdown>
    <img src="assets/images/test.svg" width="1000000">
    <figcaption>Test</figcaption>
</figure>
```

While doing this example myself, I somehow can't get the figure markdown to display the svg. This is the exact same way how I did it with my documentation that is soon to be published ([Reference](https://squidfunk.github.io/mkdocs-material/reference/images/)). After `mkdocs build`  `test.svg` appears in site/assets/images/... 

Ok wow I found the cause. I take the full embarrassment:
```python
if __name__ == "__main__":
    ...
```
I should go sleep. Everything works as intended. Thank you very much.
