### ISSUE TITLE
Feature request: Passing arguments to the scripts.

### ISSUE THREAD

**Issue by sksg** [oprypin/mkdocs-gen-files#30]
# Why
I like using gen-files, and I am using it with literate-nav in multiple projects. However, only 1-5 lines of the script code are unique to each project. These lines could easily be replaced by passing arguments to the scripts instead.

# Proposal
Use white space to separate the arguments just like when invoking with python in the shell, e.g. `python3 docs/api_reference/.generate.py my_python_package`. An example `mkdocs.yml`:
```yaml
...
plugins:
  - gen-files:
      scripts:
        - docs/.index.py my_main_readme_file my_contributing_file my_install_file
        - docs/api_reference/.generate.py my_python_package
        - docs/examples/.generate.py my_examples_folder
...
```
Similar to shell invocation, if the scripts themselves have spaces in their names you would need to quote the script, e.g. : 
```yaml
...
plugins:
  - gen-files:
      scripts:
        - "\"docs/api_reference/.generate the api.py\" my_python_package"
...
```
I think this is acceptable, since the user already is/should be wary of using spaces in file names.

With arguments passing, each of my projects would have identical scripts but unique arguments in the `mkdocs.yml`.

Note that the beginning `.` in the script names is just to make `mkdocs` not copy the python scripts over to `site`.
