### ISSUE TITLE
Support empty first item, to create section contents?

### ISSUE THREAD

**Issue by pawamoy** [oprypin/mkdocs-gen-files#31]
Without literate-nav, I do this in `nav`:

```yaml
    - Layouts:
      - manual/commands/api/layouts/index.md
      - Bsp: manual/commands/api/layouts/bsp.md
      - Columns: manual/commands/api/layouts/columns.md
```

(I use your section-index plugin)

How would I go about doing the same with literate-nav and gen-files?

If I do the following:

```yaml
    - Layouts: manual/commands/api/layouts/
```

...and write this SUMMARY.md manually:

```md
* [](index.md)
* [Bsp](bsp.md)
* [Columns](columns.md)
```

...it works. But I don't think I can programmatically create such a literate nav with gen-files:

```python
nav = mkdocs_gen_files.Nav()

nav[()] = "index.md"  # error
nav[""] = "index.md"  # error
```

**Comment by oprypin** [comment]
The solution in mkdocs_literate_nav for this is:

* Omit `index.md`.
* Specify `implicit_index`.

   ```yaml
   plugins:
     - literate-nav:
         nav_file: SUMMARY.md
         implicit_index: true
   ```

* Write this `SUMMARY.md`:

   ```markdown
   * [Bsp](bsp.md)
   * [Columns](columns.md)
   ```

---

Bonus style points for actual literate nav:

*  ```yaml
   plugins:
     - literate-nav:
         nav_file: index.md
         implicit_index: true
   ```

* Write this `index.md` manually:

  ```markdown
  # Layout objects

  Layouts position windows according to x x x

  These are the available layout objects:

  <!--nav-->
   * [Bsp](bsp.md)
   * [Columns](columns.md)
